name: Build and Publish

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "*.md"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: nchunlplab
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        working-directory: image
        run: |
          docker build -t nchunlplab/ml-dev:cu10.2-py36-tf2.3.4-torch1.9.0-jupyterlab-vscode -f cu10.2-py36-tf2.3.4-torch1.9.0-jupyterlab-vscode.Dockerfile .
          docker build -t nchunlplab/ml-dev:cu11.0-py36-tf2.4.3-torch1.7.1-jupyterlab-vscode -f cu11.0-py36-tf2.4.3-torch1.7.1-jupyterlab-vscode.Dockerfile .
          docker build -t nchunlplab/ml-dev:cu11.1-py36-tf2.6.0-torch1.9.0-jupyterlab-vscode -f cu11.1-py36-tf2.6.0-torch1.9.0-jupyterlab-vscode.Dockerfile .
      - name: Push
        run: |
          docker push nchunlplab/ml-dev:cu10.2-py36-tf2.3.4-torch1.9.0-jupyterlab-vscode
          docker push nchunlplab/ml-dev:cu11.0-py36-tf2.4.3-torch1.7.1-jupyterlab-vscode
          docker push nchunlplab/ml-dev:cu11.1-py36-tf2.6.0-torch1.9.0-jupyterlab-vscode
