name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_cu100:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build -t=p208p2002/docker-for-ai-dev-test:cu10.0-py36-tf1.14.0-torch1.3-jupyter-vscode cu10.0-py36-tf1.14.0-torch1.3-jupyter-vscode/
    - name: Push    
    - uses: elgohr/Publish-Docker-Github-Action@master
      with:
          name: p208p2002/docker-for-ai-dev-test:cu10.0-py36-tf1.14.0-torch1.3-jupyter-vscode
          username: p208p2002
          password: ${{ secrets.DOCKER_HUB_PWD }}
  
#   build_cu101:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Build cu101
#       run: docker build -t=p208p2002/cu10.1-py36-tf2.1.0-torch1.4-jupyter-vscode cu10.1-py36-tf2.1.0-torch1.4-jupyter-vscode/
  
#   Docker_Publish:
#     runs-on: [ubuntu-latest]
#     needs: [build_cu100, build_cu101]
#     steps:
#       - uses: actions/checkout@v2
#       - uses: elgohr/Publish-Docker-Github-Action@master
#         with:
#           name: p208p2002/cu10.1-py36-tf2.1.0-torch1.4-jupyter-vscode
#           username: p208p2002
#           password: ${{ secrets.DOCKER_HUB_PWD }}
