name: Build and Publish

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "*.md"
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 1 * *'

jobs:
  monthly_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      uses: azure/docker-login@v1
      with:
        username: udiclab
        password: ${{ secrets.DOCKER_HUB_PWD }}
    - name: Build
      run: |
        docker build -t=udiclab/docker-for-ai-dev:cu10.0-py36-tf1.14.0-torch1.3-jupyter-vscode -f cu10.0-py36-tf1.14.0-torch1.3-jupyter-vscode .
        docker build -t=udiclab/docker-for-ai-dev:cu10.1-py36-tf2.3.1-torch1.7.0-jupyter-vscode -f cu10.1-py36-tf2.3.1-torch1.7.0-jupyter-vscode .
        docker build -t=udiclab/docker-for-ai-dev:cu11.0-py36-tf2.3.1-torch1.7.1-jupyter-vscode -f cu11.0-py36-tf2.3.1-torch1.7.1-jupyter-vscode .
    - name: Push
      run: |
        docker push udiclab/docker-for-ai-dev:cu10.0-py36-tf1.14.0-torch1.3-jupyter-vscode
        docker push udiclab/docker-for-ai-dev:cu10.1-py36-tf2.3.1-torch1.7.0-jupyter-vscode
        docker push udiclab/docker-for-ai-dev:cu11.0-py36-tf2.3.1-torch1.7.1-jupyter-vscode
