name: Build and Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build_cu100:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      uses: azure/docker-login@v1
      with:
        username: p208p2002
        password: ${{ secrets.DOCKER_HUB_PWD }}
    - name: Build
      run: docker build -t=p208p2002/docker-for-ai-dev:cu11.0-py36-nightly-jupyter-vscode -f cu11.0-py36-nightly-jupyter-vscode .
    - name: Push
      run: docker push p208p2002/docker-for-ai-dev:cu11.0-py36-nightly-jupyter-vscode